### ISSUE TITLE
Cannot build.py in nndistance

### ISSUE THREAD

**Issue by david5duris** [ThibaultGROUEIX/AtlasNet#1]
When I run python nndistance/build.py, I get the following error:
error: /home/user/AtlasNet/nndistance/src/nnd_cuda.cu.o: No such file or directory

Full log:
Including CUDA code.
/home/user/AtlasNet/nndistance
generating /tmp/tmpvnh57h5f/_my_lib.c
setting the current directory to '/tmp/tmpvnh57h5f'
running build_ext
building '_my_lib' extension
creating home
creating home/user
creating home/user/AtlasNet
creating home/user/AtlasNet/nndistance
creating home/user/AtlasNet/nndistance/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -c _my_lib.c -o ./_my_lib.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -c /home/user/AtlasNet/nndistance/src/my_lib.c -o ./home/user/AtlasNet/nndistance/src/my_lib.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -c /home/user/AtlasNet/nndistance/src/my_lib_cuda.c -o ./home/user/AtlasNet/nndistance/src/my_lib_cuda.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 ./_my_lib.o ./home/user/AtlasNet/nndistance/src/my_lib.o ./home/user/AtlasNet/nndistance/src/my_lib_cuda.o /home/user/AtlasNet/nndistance/src/nnd_cuda.cu.o -o ./_my_lib.so
x86_64-linux-gnu-gcc: error: /home/user/AtlasNet/nndistance/src/nnd_cuda.cu.o: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 207, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by ThibaultGROUEIX** [comment]
You need to compile nnd_cuda.cu with nvcc (pytorch doesn't do it on its own).

**Comment by david5duris** [comment]
Thank you Thibault!
