### ISSUE TITLE
Trouble downloading shapenet points data

### ISSUE THREAD

**Issue by yifita** [ThibaultGROUEIX/AtlasNet#13]
Hi,
Anyone else having trouble downloading the custom shapenet point data? 
I keep getting network error in my attempts to download the shapenet data.
I suspect it's because the size is too large. Could you upload them in parts? 
Best,

**Comment by ThibaultGROUEIX** [comment]
hi, you could try doing it with command line : wget https://cloud.enpc.fr/s/j2ECcKleA1IKNzk/download --no-check-certificate
best regards,
Thibault

**Comment by yifita** [comment]
thanks that worked :+1:
