### ISSUE TITLE
normalized mesh

### ISSUE THREAD

**Issue by yifita** [ThibaultGROUEIX/AtlasNet#14]
Hi Thibault, 
another question regarding your data. 
In the normalised mesh zip, there are only very few meshes available. Are these for demonstration purposes? 
Did you do any preprocessing to the original shapenet meshes before sampling the points?

**Comment by ThibaultGROUEIX** [comment]
quick reply : there are about 20 meshes by catégory, used to compute the metro distance, reported in the paper. they should be shapenet meshes, centered and normalized to unit ball. i'll confirm this when i get back from hollidays. 
best regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Hi @yifita I confirm the statement above,
Best regards,
Thibault
