### ISSUE TITLE
Cannot download the point cloud data

### ISSUE THREAD

**Issue by jjpark** [ThibaultGROUEIX/AtlasNet#15]
Hi! I'm trying to download the point cloud data provided in this link:
https://cloud.enpc.fr/s/j2ECcKleA1IKNzk
but the network fails every time I try to download.

Do you know what's going on or how to download them?

Thank you in advance!

**Comment by jjpark** [comment]
Also, how did you normalize the original ShapeNet mesh before you sample the surface points?

Thanks!

**Comment by ThibaultGROUEIX** [comment]
hi @jjpark,

(1) have you tried 
```wget link --no-check-certificate ``` ?

(2) i sampled the points on the mesh, then center the point cloud and normalize the point cloud to unit ball.

best

Thibault

**Comment by jjpark** [comment]
Hi @ThibaultGROUEIX thank you for your reponse! So, this means that the normalization is affected by the sampled points, which means that it will change with different point sampling strategy?

**Comment by jjpark** [comment]
Also, I have successfully downloaded the files thank you!

**Comment by ThibaultGROUEIX** [comment]
yes, the centering step depends on the sampling of the points indeed.
best,
Thibault

**Comment by jjpark** [comment]
Thank you!

**Comment by jjpark** [comment]
Hi @ThibaultGROUEIX, can I ask another question:
where can I get the test/train split of shapenet files you used? I can't find it at R2N2 website...

Thanks in advance!

**Comment by ThibaultGROUEIX** [comment]
You can get the splits from https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/auxiliary/dataset.py#L53
Best, Thibault
