### ISSUE TITLE
About the point cloud dataset

### ISSUE THREAD

**Issue by guoyan1991** [ThibaultGROUEIX/AtlasNet#17]
I found that some of your point cloud dataset provided are missing.
Could you provide all the point cloud dataset？ or Could you tell me how to generate the point cloud dataset？ Thank you!

**Comment by ThibaultGROUEIX** [comment]
Hi @guoyan1991 ,
Thanks for your feedback. Can you be a little more specific ? What are you looking for ?
Best regards,
Thibault

**Comment by guoyan1991** [comment]
I can not find lots of .ply about cars in /customShapenet. I think you miss lots of samples in cars.

**Comment by ThibaultGROUEIX** [comment]
Can you provide 1 car file name that should be there and isn't  please?

**Comment by guoyan1991** [comment]
for example：
cf3e2dd9595c223e82b157e7120744ea
cf42b899c4fc72ffb927782fc69a1fbb
cf4fe31760e07e9cfe80d37c74be634f
cf7c57110621f87ba5642648127ea530
should have their .ply, but there is not.
There are 7497 objects in shapenetrendering, but only 3515 .ply in customshapenet

**Comment by guoyan1991** [comment]
for example：
cf3e2dd9595c223e82b157e7120744ea
cf42b899c4fc72ffb927782fc69a1fbb
cf4fe31760e07e9cfe80d37c74be634f
cf7c57110621f87ba5642648127ea530
should have their .ply, but there are not.
There are 7497 objects in shapenetrendering, but only 3515 .ply in customshapenet/02958343

**Comment by ThibaultGROUEIX** [comment]
Hi @guoyan1991 ,
Yes, this is what is printed in the terminal when the dataset is created.
``` category  02958343 files 3514 0.46878335112059766 %```.
The difference is that our customshapenet was generated  from shapenetv2 while shapenetrendering is from 3DR2N2 and shapenetv1. Half the cars were removed in shapenetv2, though it's the only category with a significant difference.
To generate customshapenet, we used the toolbox provided by O-CNN (ref 33 of the paper),
Best regards,
Thibault

**Comment by ebartrum** [comment]
Hey @ThibaultGROUEIX, ~~to generate customshapenet, was that virtualscanner from O-CNN? Do the points need to be points.ply or can they be .points format? virtualscanner produces .points, I cant see how to get .points.ply~~ Never mind I realised that you included the fork of OCNN which does this! How many views did you use to generate your scans, was it the default of 6?

**Comment by ThibaultGROUEIX** [comment]
Hi @ebartrum,
 I use 30 if I recall correctly. Feel free to reopen if you need more info,
Best regards
