### ISSUE TITLE
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered

### ISSUE THREAD

**Issue by Colin97** [ThibaultGROUEIX/AtlasNet#18]
My cuda is 9.0， pytorch is 1.0.0, and there is an illegal memory access when using chamfer distance. 

```
sys.path.append("./extension/")
import dist_chamfer as ext

distChamfer =  ext.chamferDist()

x = torch.rand(32, 2500, 3)
y = torch.rand(32, 2500, 3)
x.cuda()
y.cuda()

dis1, dis2 = distChamfer(x, y)
#dis1 = x - y

print(dis1)
```

**Comment by ThibaultGROUEIX** [comment]
Hi @Colin97 ,
can you also specify your python version please ?
The fastest solution is to try other combinations : Python 3.7 - cuda 10 - pytorch 1 is my setup. Other people in my lab use  Python 3.6 - cuda 10 - pytorch 1.
If none of the above work for you, can you paste your error ?
best regards,
Thibault

**Comment by matheusgadelha** [comment]
I am having the same error. Python 3.6, cuda 10.0, pytorch 1.

```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 66, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 277, in _str
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 195, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 228, in get_summarized_data
    return torch.stack([get_summarized_data(x) for x in (start + end)])
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 228, in <listcomp>
    return torch.stack([get_summarized_data(x) for x in (start + end)])
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 221, in get_summarized_data
    return torch.cat((self[:PRINT_OPTS.edgeitems], self[-PRINT_OPTS.edgeitems:]))
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:26
```

**Comment by matheusgadelha** [comment]
Just figured out, this was no issue with the chamferDist implementation but with the way @Colin97 is testing. From that code, `x` and `y` remain in cpu. According to the [documentation](https://pytorch.org/docs/stable/tensors.html?highlight=cuda#torch.Tensor.cuda), `.cuda()` returns a copy of the tensor in the gpu unless the tensor is already in it, so the right way to do would be to write:
```
x = x.cuda()
y = y.cuda()
dis1, dis2 = distChamfer(x, y)
```
So, just make sure your tensors are in the GPU before passing to chamferDist and it should work.

**Comment by Colin97** [comment]
> Just figured out, this was no issue with the chamferDist implementation but with the way @Colin97 is testing. From that code, `x` and `y` remain in cpu. According to the [documentation](https://pytorch.org/docs/stable/tensors.html?highlight=cuda#torch.Tensor.cuda), `.cuda()` returns a copy of the tensor in the gpu unless the tensor is already in it, so the right way to do would be to write:
> 
> ```
> x = x.cuda()
> y = y.cuda()
> dis1, dis2 = distChamfer(x, y)
> ```
> 
> So, just make sure your tensors are in the GPU before passing to chamferDist and it should work.

**Comment by Colin97** [comment]
> Just figured out, this was no issue with the chamferDist implementation but with the way @Colin97 is testing. From that code, `x` and `y` remain in cpu. According to the [documentation](https://pytorch.org/docs/stable/tensors.html?highlight=cuda#torch.Tensor.cuda), `.cuda()` returns a copy of the tensor in the gpu unless the tensor is already in it, so the right way to do would be to write:
> 
> ```
> x = x.cuda()
> y = y.cuda()
> dis1, dis2 = distChamfer(x, y)
> ```
> 
> So, just make sure your tensors are in the GPU before passing to chamferDist and it should work.

u r right！

**Comment by ThibaultGROUEIX** [comment]
Thanks @matheusgadelha  !
--Thibault
