### ISSUE TITLE
Vertices from shapenet models

### ISSUE THREAD

**Issue by BornInWater** [ThibaultGROUEIX/AtlasNet#20]
ShapeNet models have large number of vertices[eg: 26000 vertices for car models] but your model generates much lesser vertices. So, are the ground truth meshes converted to low resolution before finding the chamfer distance?
Also, some of those vertices in the ground truth correspond to the interior of the car like below
![car_interior](https://user-images.githubusercontent.com/36148827/57087492-2ddc8400-6cce-11e9-93df-81968a401d0b.png)
Do you just ignore those vertices or just let them be there for the chamfer distance calculation?
Thanks

**Comment by ThibaultGROUEIX** [comment]
Dear @BornInWater,
Please note that Atlasnet can generate as many vertices as you want by sampling the template more or less densely.
The ground truth data is generated by shooting rays outside the object using ```O-cnn:
Octree-based convolutional neural networks for 3d shape analysis```, so interior parts are ignored.
More details are in the main paper in case you are interested.
Best regards,
Thibault

**Comment by prachees** [comment]
Hi @ThibaultGROUEIX,

Thank you for sharing the code of your paper! :) I am trying to train the network on a different dataset and am using the tool (called virtualscanner -https://github.com/microsoft/O-CNN) used in the O-CNN paper to sample points from mesh. 

How many views did you use for generating the point clouds (scanning) using the tool (the parameter 'nviews' in virtualscanner)?

**Comment by ThibaultGROUEIX** [comment]
Dear @prachees,
Thanks for pointing out this missing detail in the paper.
I think around 30 views.
@techmatt do you know the exact number? 
Best regards,
Thibault

**Comment by techmatt** [comment]
The results in the paper used nviews = 32, although if I recall correctly
results looks pretty similar for nviews between 20 and greater.

--Matt
