### ISSUE TITLE
How is metro being used?

### ISSUE THREAD

**Issue by BornInWater** [ThibaultGROUEIX/AtlasNet#21]
Hi,
Based on what I read on the metro website, it seems that it a windows software and the terminal usage of it for linux is not out yet. So, did you guys do the same or you found a work around for that to make it work on linux via command line?

Thanks

**Comment by ThibaultGROUEIX** [comment]
Dear @BornInWater,
You can find the code for the metro distance here : https://github.com/RobotLocomotion/meshConverters/tree/master/vcglib/apps/metro
regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
see also https://github.com/ThibaultGROUEIX/AtlasNet/issues/34
