### ISSUE TITLE
 compile chamfer

### ISSUE THREAD

**Issue by zjxyz** [ThibaultGROUEIX/AtlasNet#23]
hi, it is an awesome job.
My ubuntu16.04 , python3.5, pytorch1.0, cuda9.2, gcc 5.4
But I get a wrong when I compile chamfer.
import torch;import chamfer;
ImportError: /usr/local/lib/python3.5/dist-packages/chamfer-0.0.0-
py3.5-linux-x86-64.egg/chamfer.cpython-35m-x86_64-linux-gnu.so:
 underfined symbol: _ZN2at5ErrorCLENs_14SourceLocationERKSs
Thanks in advance!

**Comment by mingchunZhang** [comment]
@xiayizhan2017  Hi, I got the same error as yours ，have you solved it?

**Comment by zjxyz** [comment]
> @xiayizhan2017 Hi, I got the same error as yours ，have you solved it?

I solved it with pytorch 1.1.

**Comment by mingchunZhang** [comment]
@xiayizhan2017  Thanks for your reply. Did you change other configurations?  It seems the author suggests using python 3.7

**Comment by zjxyz** [comment]
> @xiayizhan2017 Thanks for your reply. Did you change other configurations? It seems the author suggests using python 3.7
It's ok when I run it with python3.5.
