### ISSUE TITLE
How to test on my own data?

### ISSUE THREAD

**Issue by mingchunZhang** [ThibaultGROUEIX/AtlasNet#24]
Hi，

I'd like to generate some car 3d models , how to process my own car images?

Thanks in advance.

**Comment by ThibaultGROUEIX** [comment]
Hi @piri7001,
Do you want to use the trained models or retrain models on a dataset of your own?
Best regards,
Thibault

**Comment by mingchunZhang** [comment]
@ThibaultGROUEIX 

Thanks for your reply.
I want to use the trained models.

**Comment by ThibaultGROUEIX** [comment]
Looks like you're looking for `inference/demo.py --input myinput.png`. Try to match the example in `pictures/input.png` :
* transparent background (black)
* centered object
* image of size 137*137
Best regards,
Thibault

**Comment by mingchunZhang** [comment]
Hi, @ThibaultGROUEIX 
If I want to retrain models on a dataset of my own, how many objects(From the same category) do I need?

**Comment by ThibaultGROUEIX** [comment]
Hi @mingchunZhang,
The obvious answer is `as many as you can`. I don't have a clear answer for a `minimum` number of samples. It depends on the variability of your class. I'd recommend making sure that your dataset covers nicely your class manyfold by looking at hundred of examples... I you can't, then an out-of-the-box good start is around 1k samples.
Best regards,
Thibault
