### ISSUE TITLE
Where is chamfer ?

### ISSUE THREAD

**Issue by shoujieqiu** [ThibaultGROUEIX/AtlasNet#28]
I saw "import chamfer" in "extension/dist_chamfer.py",but I can't find where "chamfer" is.Could you help me?

**Comment by ThibaultGROUEIX** [comment]
The chamfer package is compiled by `cd ./extension; python setup.py install`. I compiles the CUDA sources in `extension/chamfer.cu`.
For more information, you can take a look at https://pytorch.org/tutorials/advanced/cpp_extension.html
Cheers,
Thibault

**Comment by shoujieqiu** [comment]
Thank you very much!Best wishes!
——邱守杰。


ThibaultGROUEIX <notifications@github.com> 于2019年8月27日周二 上午12:42写道：
