### ISSUE TITLE
Evaluate RGB image with pretrained model

### ISSUE THREAD

**Issue by Itamare1982** [ThibaultGROUEIX/AtlasNet#29]
Hi Iam actually try to evaluate SVR Atlas pretrained model on RGB image(chair),  my parameters are really similar to the demo and i got wird result (by view in chrom 3D viewer ).
i used the demo grid generation.
when i run your demo plane.jpg im my network i  got good results in the 3Dviewer .
![Demo plain](https://user-images.githubusercontent.com/55034751/65280552-4b08d680-db39-11e9-8e00-77943e5bfb37.PNG)
![wird_pic_1](https://user-images.githubusercontent.com/55034751/65280553-4ba16d00-db39-11e9-9def-b62b1fc20257.PNG)
![wird_pic_2](https://user-images.githubusercontent.com/55034751/65280557-4ba16d00-db39-11e9-8321-96710c7228df.PNG)
![wird_pic_3](https://user-images.githubusercontent.com/55034751/65280559-4ba16d00-db39-11e9-9570-3f1594057293.PNG)
can you please direct my how to evaluate RGB image?

**Comment by ThibaultGROUEIX** [comment]
hi @Itamare1982,
could you share your input images please?
 i think it's probably a background color issue. make sure it's the same as the demo image
cheers
Thibault

**Comment by Itamare1982** [comment]
it seems like the problem is with the background - but how can i fix it? to be as the plain demo background?
you can find attached my image
![chair](https://user-images.githubusercontent.com/55034751/65284096-4b0cd480-db41-11e9-9aa7-bdae094371ae.jpg)

**Comment by ThibaultGROUEIX** [comment]
thanks for sharing. 
You need the background to be all black or all white (don't remember which). 
there are two options : (1) retrain the models with data augmentation to deal with more diverse backgrounds (2) fix this particular image. i think it can be easily done on Photoshop

**Comment by Itamare1982** [comment]
Hi , i try to change the background ( as in the attached image) with a simple OpenCV script and i got the attached output which is also not as excpected.
any suggestion ?
![3D_output](https://user-images.githubusercontent.com/55034751/65286357-f6b92300-db47-11e9-938f-79c16ef2c0f0.PNG)
![chair_chess_board](https://user-images.githubusercontent.com/55034751/65286359-f751b980-db47-11e9-81f6-ee7d1a97cdc8.jpg)

**Comment by Itamare1982** [comment]
Black background doesnt help either
![chair_black_background](https://user-images.githubusercontent.com/55034751/65286632-f2d9d080-db48-11e9-8195-4b9456f57fdf.jpg)

**Comment by Itamare1982** [comment]
Sorry i missed your last comment about the Black/White background

**Comment by Itamare1982** [comment]
Hi - white background doesnt solve the issue also and i am continue getting bad 3D object
do you have any other suggestions?

![chair_white_background](https://user-images.githubusercontent.com/55034751/65288009-e015ca80-db4d-11e9-963d-e25d7df4f536.jpg)
![white_background_output](https://user-images.githubusercontent.com/55034751/65288018-e7d56f00-db4d-11e9-96c4-381a35270ab0.PNG)

**Comment by ThibaultGROUEIX** [comment]
I removed the background with the instant alpha of preview in mac then gave it to demo. It seems not great but reasonable.
![4412](https://user-images.githubusercontent.com/11445067/65308144-b9758500-db89-11e9-9d84-4ca742e9b172.png)
![65286632-f2d9d080-db48-11e9-8195-4b9456f57fdf](https://user-images.githubusercontent.com/11445067/65308146-b9758500-db89-11e9-845d-990645e1f6cf.png)

**Comment by Itamare1982** [comment]
OK ,thank you very much for the help and for the sharing, i do get better result without background but it still not as expected , i will continue to improve it and get better results.

Thank you for the productive suggestions
