### ISSUE TITLE
Using my own data

### ISSUE THREAD

**Issue by acerio98** [ThibaultGROUEIX/AtlasNet#31]
I would like to train the network on my own data, but am not finding many hints on how I might do it. If I were to do this (if it's possible), for each data example, would I need to have for all of: point clouds+normals, normalized meshes, and rendered views like is mentioned for ShapeNet in the README? Or do I only need some of these? I would appreciate it if you could tell me what exactly I would need to train on my own data and if you have any tips.

**Comment by ThibaultGROUEIX** [comment]
Hi @acerio98,
If you want to train the autoencoder, you need 3D point clouds
If you want to train the single-view-reconstruction, you need 3D point clouds + renderings,
Let me know if you have further questions,
Thibault
PS : I'll release an upgraded version of the code in a few months and keep in mind to include the possibility to seamlessly train on your own data

**Comment by acerio98** [comment]
Hm..I tried just putting my data in the ShapeNet folders but the `dataset.py` script seems to be checking for renderings even if I only want the autoencoder. To train on my own data for the autoencoder, do I have to add my own class to `dataset.py`? If so, I'm not really sure what parts I can copy from the ShapeNet class definition and what I would have to redefine for my own class definition. Do you have any suggestions?

**Comment by ThibaultGROUEIX** [comment]
If you want to train on your own data, it's probably easier to write your own dataloader.
