### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by spha-code** [ThibaultGROUEIX/AtlasNet#33]
Thank you for the great work!
I get this error below when I run: ./training/train_AE_AtlasNet.py

I checked two more similar issues but this looks different. Any idea how to solve it? Any help appreciated!

  File "./training/train_AE_AtlasNet.py", line 151, in <module>
    dist1, dist2 = distChamfer(points.transpose(2,1).contiguous(), pointsReconstructed) #loss function
  File "./training/train_AE_AtlasNet.py", line 64, in distChamfer
    P = (rx.transpose(2,1) + ry - 2*zz)
RuntimeError: CUDA error: out of memory

I run pytorch:0.4.1 / Ubuntu 18.04

FULL CODE:

`(pytorch-atlasnet) user@user-FB-22866-One-Computer-Core-i5-46:~/AtlasNet$ python ./training/train_AE_AtlasNet.py --env $env --nb_primitives $nb_primitives |& tee ${env}.txt
Setting up a new session...
Namespace(accelerated_chamfer=0, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Random Seed:  314
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
{'plane': '02691156', 'bench': '02828884', 'cabinet': '02933112', 'car': '02958343', 'chair': '03001627', 'monitor': '03211117', 'lamp': '03636649', 'speaker': '03691459', 'firearm': '04090263', 'couch': '04256520', 'table': '04379243', 'cellphone': '04401088', 'watercraft': '04530566'}
category  02691156 files 4044 0.999752781211372 %
category  02828884 files 1813 0.9983480176211453 %
category  02933112 files 1571 0.9993638676844784 %
category  02958343 files 3514 0.46878335112059766 %
category  03001627 files 6778 1.0 %
category  03211117 files 1093 0.9981735159817352 %
category  03636649 files 2309 0.9961173425366695 %
category  03691459 files 1597 0.9870210135970334 %
category  04090263 files 2373 1.0 %
category  04256520 files 3173 1.0 %
category  04379243 files 8436 0.9914208485133388 %
category  04401088 files 1050 0.9980988593155894 %
category  04530566 files 1939 1.0 %
training set 31747
testing set 7943
**Traceback (most recent call last):
  File "./training/train_AE_AtlasNet.py", line 151, in <module>
    dist1, dist2 = distChamfer(points.transpose(2,1).contiguous(), pointsReconstructed) #loss function
  File "./training/train_AE_AtlasNet.py", line 64, in distChamfer
    P = (rx.transpose(2,1) + ry - 2*zz)
RuntimeError: CUDA error: out of memory**
`

**Comment by ThibaultGROUEIX** [comment]
Dear @spha-code 
Can you share the specs of your gpu ? You can check them with `nvidia-smi`. I would like to know your gpu memory,
Best regards,
Thibault

**Comment by spha-code** [comment]
many thanks for the response!

Here you go:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.116                Driver Version: 390.116                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
| 15%   54C    P8    16W / 151W |    947MiB /  8116MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1477      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1524      G   /usr/bin/gnome-shell                          51MiB |
|    0      1723      G   /usr/lib/xorg/Xorg                           164MiB |
|    0      1869      G   /usr/bin/gnome-shell                         114MiB |
|    0      2325      G   ...uest-channel-token=16564093330129296362   594MiB |
+-----------------------------------------------------------------------------+

**Comment by spha-code** [comment]
Dear @ThibaultGROUEIX,

when I run **./training/train_AE_AtlasNet.py** after rebooting, for the first time, I don't get the error but the process stops at this line:

".................
training set 31747
testing set 7943"

and I don't see anything happening on the visdom http://localhost:8888/

Any hints?

Thanks for your responses!

**Comment by ThibaultGROUEIX** [comment]
It could be that you're running out of memory. I see you have 7GB free. It would be coherent with the fact that it works after rebooting (Xorg takes less memory).
You should try with the CUDA version of the chamfer's distance : it takes less memory.

**Comment by ThibaultGROUEIX** [comment]
Ie. with `--accelerated_chamfer 1`

**Comment by spha-code** [comment]
Many thanks for the responses! I get this error below when I give --accelerated_chamfer 1

`(pytorch-atlasnet) user@user-FB-22866-One-Computer-Core-i5-46:~/AtlasNet$ python ./training/train_AE_AtlasNet.py --accelerated_chamfer 1
Namespace(accelerated_chamfer=1, batchSize=32, env='AE_AtlasNet', model='', nb_primitives=25, nepoch=120, num_points=2500, super_points=2500, workers=12)
Traceback (most recent call last):
  File "./training/train_AE_AtlasNet.py", line 37, in <module>
    import dist_chamfer as ext
  File "./extension/dist_chamfer.py", line 8, in <module>
    import chamfer
ImportError: /home/user/anaconda3/envs/pytorch-atlasnet/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs
`

**Comment by ThibaultGROUEIX** [comment]
can you test just 
```
python -c "import torch; import chamfer"
```
Did you hit errors when you compiled the CUDA extension?

**Comment by spha-code** [comment]
(pytorch-atlasnet) user@user-FB-22866-One-Computer-Core-i5-46:~/AtlasNet$ python -c "import torch; import chamfer"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/user/anaconda3/envs/pytorch-atlasnet/lib/python3.7/site-packages/chamfer-0.0.0-py3.7-linux-x86_64.egg/chamfer.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

import torch  - no error
import chamfer - see above

No errors when I compiled the CUDA extension..

**Comment by spha-code** [comment]
I read this online related to the above error:

"It is possible that the compiling environment and runtime environment are not the same."

**Comment by ThibaultGROUEIX** [comment]
Ha ok I think i got it :
can you run : 
`python -c "import torch; torch.version.cuda" and check witch version of cuda you have in '/usr/local/' ? it should match.

**Comment by spha-code** [comment]
(pytorch-atlasnet) user@user-FB-22866-One-Computer-Core-i5-46:~$ python -c "import torch; print(torch.version.cuda)"
9.0.176


(pytorch-atlasnet) user@user-FB-22866-One-Computer-Core-i5-46:/usr/local/cuda-9.0$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

it seems to match..

**Comment by spha-code** [comment]
Thanks a lot for the patience...

**Comment by spha-code** [comment]
it works!! and I get visuals in visdom!!

I downgraded the pytorch version from 0.4.1 to 0.4.0 :

conda install pytorch=0.4.0 cuda90 -c pytorch

pip install pandas
pip install visdom 

cd ./extension
python setup.py install

Thanks a lot for your help!

**Comment by ThibaultGROUEIX** [comment]
Great ! 
You're up and running, best of luck for the rest :)

**Comment by spha-code** [comment]
Thanks!! Very exciting! I appreciate your help!
