### ISSUE TITLE
What are the forward_inference_from_latent_space() functions used for?

### ISSUE THREAD

**Issue by acerio98** [ThibaultGROUEIX/AtlasNet#35]
I noticed that in `auxiliary/model.py` some of the models, for example AE_AtlasNet have an extra training function called `forward_inference_from_latent_space()`, however I can't find it used anywhere. What is this special training function supposed to do?

**Comment by ThibaultGROUEIX** [comment]
Dear acerio,
There are a few class method that i use for part of the code I did not release. This particular fonction is used to decode from a latent vector. I used it for latent vector interpolation to generate these videos : https://www.youtube.com/watch?v=kp59GLjZUWM
Best regards,
Thibault
