### ISSUE TITLE
Other trained models are not loading successfully 

### ISSUE THREAD

**Issue by ujjawalcse** [ThibaultGROUEIX/AtlasNet#37]
Thank you very much for posting this repo.
I used demo.py with different input image and it's generating meshes as well. 
Also, I could use only **svr_atlas_25.pth**  which is default. When I tried other trained models like **ae_atlasnet_25.pth** and other couldn't be loaded successfully.
It raising error as:

Traceback (most recent call last):
  File "inference/demo.py", line 43, in <module>
    **network.load_state_dict(torch.load(opt.model))**
  File "/home/wowexp/anaconda3/envs/kaolin/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SVR_AtlasNet:
	Missing key(s) in state_dict: "encoder.conv1.weight", "encoder.bn1.weight", "encoder.bn1.bias", "encoder.bn1.running_mean", "encoder.bn1.running_var", "encoder.layer1.0.conv1.weight", "encoder.layer1.0.bn1.weight", "encoder.layer1.0.bn1.bias", "encoder.layer1.0.bn1.running_mean", "encoder.layer1.0.bn1.running_var", "encoder.layer1.0.conv2.weight", "encoder.layer1.0.bn2.weight", "encoder.layer1.0.bn2.bias", "encoder.layer1.0.bn2.running_mean", "encoder.layer1.0.bn2.running_var", "encoder.layer1.1.conv1.weight", "encoder.layer1.1.bn1.weight", "encoder.layer1.1.bn1.bias", "encoder.layer1.1.bn1.running_mean", "encoder.layer1.1.bn1.running_var", "encoder.layer1.1.conv2.weight", "encoder.layer1.1.bn2.weight", "encoder.layer1.1.bn2.bias", "encoder.layer1.1.bn2.running_mean", "encoder.layer1.1.bn2.running_var", "encoder.layer2.0.conv1.weight", "encoder.layer2.0.bn1.weight", "encoder.layer2.0.bn1.bias", "encoder.layer2.0.bn1.running_mean", "encoder.layer2.0.bn1.running_var", "encoder.layer2.0.conv2.weight", "encoder.layer2.0.bn2.weight", "encoder.layer2.0.bn2.bias", "encoder.layer2.0.bn2.running_mean", "encoder.layer2.0.bn2.running_var", "encoder.layer2.0.downsample.0.weight", "encoder.layer2.0.downsample.1.weight", "encoder.layer2.0.downsample.1.bias", "encoder.layer2.0.downsample.1.running_mean", "encoder.layer2.0.downsample.1.running_var", "encoder.layer2.1.conv1.weight", "encoder.layer2.1.bn1.weight", "encoder.layer2.1.bn1.bias", "encoder.layer2.1.bn1.running_mean", "encoder.layer2.1.bn1.running_var", "encoder.layer2.1.conv2.weight", "encoder.layer2.1.bn2.weight", "encoder.layer2.1.bn2.bias", "encoder.layer2.1.bn2.running_mean", "encoder.layer2.1.bn2.running_var", "encoder.layer3.0.conv1.weight", "encoder.layer3.0.bn1.weight", "encoder.layer3.0.bn1.bias", "encoder.layer3.0.bn1.running_mean", "encoder.layer3.0.bn1.running_var", "encoder.layer3.0.conv2.weight", "encoder.layer3.0.bn2.weight", "encoder.layer3.0.bn2.bias", "encoder.layer3.0.bn2.running_mean", "encoder.layer3.0.bn2.running_var", "encoder.layer3.0.downsample.0.weight", "encoder.layer3.0.downsample.1.weight", "encoder.layer3.0.downsample.1.bias", "encoder.layer3.0.downsample.1.running_mean", "encoder.layer3.0.downsample.1.running_var", "encoder.layer3.1.conv1.weight", "encoder.layer3.1.bn1.weight", "encoder.layer3.1.bn1.bias", "encoder.layer3.1.bn1.running_mean", "encoder.layer3.1.bn1.running_var", "encoder.layer3.1.conv2.weight", "encoder.layer3.1.bn2.weight", "encoder.layer3.1.bn2.bias", "encoder.layer3.1.bn2.running_mean", "encoder.layer3.1.bn2.running_var", "encoder.layer4.0.conv1.weight", "encoder.layer4.0.bn1.weight", "encoder.layer4.0.bn1.bias", "encoder.layer4.0.bn1.running_mean", "encoder.layer4.0.bn1.running_var", "encoder.layer4.0.conv2.weight", "encoder.layer4.0.bn2.weight", "encoder.layer4.0.bn2.bias", "encoder.layer4.0.bn2.running_mean", "encoder.layer4.0.bn2.running_var", "encoder.layer4.0.downsample.0.weight", "encoder.layer4.0.downsample.1.weight", "encoder.layer4.0.downsample.1.bias", "encoder.layer4.0.downsample.1.running_mean", "encoder.layer4.0.downsample.1.running_var", "encoder.layer4.1.conv1.weight", "encoder.layer4.1.bn1.weight", "encoder.layer4.1.bn1.bias", "encoder.layer4.1.bn1.running_mean", "encoder.layer4.1.bn1.running_var", "encoder.layer4.1.conv2.weight", "encoder.layer4.1.bn2.weight", "encoder.layer4.1.bn2.bias", "encoder.layer4.1.bn2.running_mean", "encoder.layer4.1.bn2.running_var", "encoder.fc.weight", "encoder.fc.bias". 
	Unexpected key(s) in state_dict: "encoder.0.stn.conv1.weight", "encoder.0.stn.conv1.bias", "encoder.0.stn.conv2.weight", "encoder.0.stn.conv2.bias", "encoder.0.stn.conv3.weight", "encoder.0.stn.conv3.bias", "encoder.0.stn.fc1.weight", "encoder.0.stn.fc1.bias", "encoder.0.stn.fc2.weight", "encoder.0.stn.fc2.bias", "encoder.0.stn.fc3.weight", "encoder.0.stn.fc3.bias", "encoder.0.conv1.weight", "encoder.0.conv1.bias", "encoder.0.conv2.weight", "encoder.0.conv2.bias", "encoder.0.conv3.weight", "encoder.0.conv3.bias", "encoder.0.bn1.weight", "encoder.0.bn1.bias", "encoder.0.bn1.running_mean", "encoder.0.bn1.running_var", "encoder.0.bn2.weight", "encoder.0.bn2.bias", "encoder.0.bn2.running_mean", "encoder.0.bn2.running_var", "encoder.0.bn3.weight", "encoder.0.bn3.bias", "encoder.0.bn3.running_mean", "encoder.0.bn3.running_var", "encoder.1.weight", "encoder.1.bias", "encoder.2.weight", "encoder.2.bias", "encoder.2.running_mean", "encoder.2.running_var".

**Comment by ThibaultGROUEIX** [comment]
Dear @ujjawalcse 
Yes i've run into this one as well, i suspect that it's a recent pytorch issue. I refactored the code, so you might want to try again and see if you can avoid this issue.
Best regards,
Thibault
