### ISSUE TITLE
Cannot clone on Windows

### ISSUE THREAD

**Issue by dneuhof** [ThibaultGROUEIX/AtlasNet#4]
When trying to clone the repo to Windows I get the following error:
```
fatal: cannot create directory at 'aux': Invalid argument
warning: Clone succeeded, but checkout failed.
```
This is because `aux` is a reserved name on Windows.
I don't know of a solution to this problem (except from changing the name of the directory).

**Comment by ThibaultGROUEIX** [comment]
Hi @davidneuhof. Thanks for letting me know, i've updated aux to auxiliary.  The cloning should work now. Let me know if you manage to get it to work on windows please.

**Comment by ThibaultGROUEIX** [comment]
@davidneuhof Can you please confirm your issue is solved and close it if that's the case ?

**Comment by dneuhof** [comment]
@ThibaultGROUEIX , thank you.

**Comment by ThibaultGROUEIX** [comment]
No pb. By the way, pytorch is now officially supported on windows as of version 4. Beware though that the chamfer distance code only work for a specific commit of version 4 (I can't figure out the exact issue unfortunatly).
