### ISSUE TITLE
train AtlasNet on own dataset

### ISSUE THREAD

**Issue by qiminchen** [ThibaultGROUEIX/AtlasNet#41]
Hi,

Is it possible to train the AtlasNet on our own dataset? If so, what data should I generate if I have 2D RGB images and corresponding 3D objects? And I only want to synthesize a mesh from a single image. Thanks

**Comment by ThibaultGROUEIX** [comment]
Hi @qiminchen. Happy new year !
You have to replace atlasnet dataloader `AtlasNet/dataset/dataset_shapenet.py` with your own dataloader. It should output a python dictionary with the entry keys `image`, `points`, `pointcloud_path`, `image_path`, `name`, and `category`.
Cheers,
Thibault
