### ISSUE TITLE
training with a single gpu did not work initially

### ISSUE THREAD

**Issue by ebartrum** [ThibaultGROUEIX/AtlasNet#43]
I was training with the following command:
`python train.py --class_choice=car --dir_name log/atlasnet_singleview_25_squares_tmp --nb_primitives 25 --template_type SQUARE --SVR --reload_decoder_path training/trained_models/atlasnet_autoencoder_25_squares/network.pth   --train_only_encoder --multi_gpu 0`
I got a map location error, when loading the weights. I had to make the following change to model/trainer_model.py, line 49
-            network.module.load_state_dict(torch.load(opt.reload_decoder_path))
+            network.module.load_state_dict(torch.load(opt.reload_decoder_path, map_location='cuda:0'))

**Comment by ThibaultGROUEIX** [comment]
Hi ! Thanks for the feedback.
Both version work fine for me so i incorporated your change in the latest commit.
Feel free to give me any further feedback
The new version of the code is not a unanimous improvement. cf #42 
Cheers,
Thibault
