### ISSUE TITLE
There are no renderings for "bottle" class

### ISSUE THREAD

**Issue by AnailadS** [ThibaultGROUEIX/AtlasNet#44]
Hi! I'm  trying to train the network only on the "bottle" class, but it downloads just the pointcloud files and no renderings.

**Comment by ThibaultGROUEIX** [comment]
Dear @AnailadS , 
Yes, there are only renderings for these 13 categories (From 2D-R2N2, Choy et al.). plane, bench, cabinet, car, chair, monitor, lamp, speaker, firearm, couch, table, cellphone, watercraft.
If you're specifically interested in the bottle category, you can use one the following softwares to script rendering : blender, open3D, mistuba..
Best regards,
Thibault
