### ISSUE TITLE
Is AtlasNet deploy able in clusters.

### ISSUE THREAD

**Issue by chinmoybasak** [ThibaultGROUEIX/AtlasNet#45]
Goodday.
just wondering if the code can be deployed in the cluster with GPU.

Best,
Chinmoy

**Comment by ThibaultGROUEIX** [comment]
Hi @chinmoybasak 
yes the code supports multiple GPU training. (and has been tested in that setting). Let me know if you need further help,
Best,
Thibault

**Comment by ch1253** [comment]
Thank you for your reply. Can you please direct me any resource so I can train my model in Alabma Super Computer.

http://webcache.googleusercontent.com/search?q=cache:fn8oafyFYJkJ:www.asc.edu/sites/default/files/org_sections/HPC/documents/manHPC_0.pdf+&cd=1&hl=en&ct=clnk&gl=us

**Comment by chinmoybasak** [comment]
Thank you for your reply. Can you please direct me any resource so I can train my model in Alabma Super Computer.

http://webcache.googleusercontent.com/search?q=cache:fn8oafyFYJkJ:www.asc.edu/sites/default/files/org_sections/HPC/documents/manHPC_0.pdf+&cd=1&hl=en&ct=clnk&gl=us

**Comment by ThibaultGROUEIX** [comment]
I have no idea, it is beyond the scope of the current code.
You might want to convert the code to [pytorch lightning](https://github.com/PyTorchLightning/pytorch-lightning) which makes large-scale deployment easier (or so I heard).
Best
Thibault
