### ISSUE TITLE
Dataset Split used for AtlasNet

### ISSUE THREAD

**Issue by KunalMGupta** [ThibaultGROUEIX/AtlasNet#47]
Hi,

I am wondering which dataset split was used for training the AtlasNet model presented in the original paper. As per my understanding, the paper claims to be using the split earlier used by [3DR2N2](https://github.com/chrischoy/3D-R2N2) paper. However, I am not able to find the split file anywhere in their repository. I could only find the code [here](https://github.com/ThibaultGROUEIX/AtlasNet/blob/8c589f2b7c42ec5c85e39bf2c749700a636e2e04/dataset/dataset_shapenet.py#L92) which seems to be dealing with any dataset split. However, I do not believe that this is the same as that of 3DR2N2.  Additionally, the authors of [Occupancy Network](https://arxiv.org/abs/1812.03828) mention in their paper that they could only evaluate pretrained AtlasNet model for a part of the 3DR2N2 dataset.  I have checked the overlap of dataset split used by [MeshRCNN](https://arxiv.org/abs/1906.02739), [Occupancy Network](https://arxiv.org/abs/1812.03828) (both of which use 3DR2N2's data split and are consistent with each other) and the one generated from  [here](https://github.com/ThibaultGROUEIX/AtlasNet/blob/8c589f2b7c42ec5c85e39bf2c749700a636e2e04/dataset/dataset_shapenet.py#L92) and I believe that they do not have any significant overlap. I am therefore not sure which dataset split is used by AtlasNet. Is it possible to share a JSON file of the dataset split used?

Thanks.

**Comment by ThibaultGROUEIX** [comment]
Hi @KunalMGupta,
The original AtlasNet implem (check the tags) used ShapeNetv2 while 3Dr2n2 used shapenetv1, which meant the splits where different. I reverted Atlasnet code to Shapenetv1 at the end of 2019 so the splits should now be [identical](https://github.com/chrischoy/3D-R2N2/blob/7522834a6d155ac5c30e3119e3747f0967b299d2/lib/config.py#L46) with 3D-r2n2.
Best regards,
Thibault

**Comment by KunalMGupta** [comment]
I see. Thanks a lot for clearing the confusion.
