### ISSUE TITLE
What's the meaning of conv1d with the same input and output size

### ISSUE THREAD

**Issue by BrandoZhang** [ThibaultGROUEIX/AtlasNet#48]
Hi, thanks for your great work!
When I studied your code, I found the following:
https://github.com/ThibaultGROUEIX/AtlasNet/blob/8dd00e940dae208209ae97b6694e647eb5b1a06b/auxiliary/model.py#L132
I am wondering what's the meaning of 1d convolution that takes the same size of input and output.

**Comment by ThibaultGROUEIX** [comment]
Dear @BrandoZhang ,

it's like a fully connected layer with `self.bottleneck_size` input neurons and `self.bottleneck_size` output neurons. You can check out pytorch doc on [conv1d.](https://pytorch.org/docs/stable/nn.html?highlight=conv1d#torch.nn.Conv1d)

Best,
Thibault
