### ISSUE TITLE
jacobian_regularization branch: Demo fails, many bugs.

### ISSUE THREAD

**Issue by Howardyangyixuan** [ThibaultGROUEIX/AtlasNet#49]
![image](https://user-images.githubusercontent.com/44062498/81934599-cca9f900-9621-11ea-8926-c2aa05565594.png)
python train.py --demo --demo_input_path /media/vrlab/out/aimi/AtlasNet/demo/Chair-PNG-Transparent.png --reload_model_path /media/vrlab/out/aimi/AtlasNet/demo/trained_models/atlasnet_jacobian_noregul/
Jitting Chamfer 3D
Loaded JIT 3D CUDA chamfer distance
Launching new HTTP instance in port 8891
TMUX=0 tmux new-session -d -s http_server \; send-keys "/home/vrlab/.conda/envs/atlasnet/bin/python -m http.server -p 8891 > /dev/null 2>&1" Enter
duplicate session: http_server
Setting up a new session...
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer = trainer.Trainer(opt)
  File "/media/vrlab/out/aimi/AtlasNet/training/trainer.py", line 29, in __init__
    os.mkdir(self.opt.training_media_path)
FileNotFoundError: [Errno 2] No such file or directory: 'log/02020-05-14T20:30:33.630591/training_media'

opt.dir_path is "log/02020-05-14T20:30:33.630591"
![image](https://user-images.githubusercontent.com/44062498/81934858-3f1ad900-9622-11ea-8f4c-bd31e74830e3.png)
although change it to opt.reload_model_path could help, there are other similar problem. 
Does anyone have the same problem?

**Comment by ThibaultGROUEIX** [comment]
Interesting let me test it.

**Comment by ThibaultGROUEIX** [comment]
You can git pull.

I've tested training both autoencoder and SVR, and fixed path and reload issue in the demo.
You can now try : `python train.py --demo --demo_input YOUR_PATH.obj --reload_model_path YOUR_PATH/network.pth --template_type SQUARE`

Note that the pretrained models are only autoencoders. If you want to do single-view, you have to train new models.

Best regards,
Thibault

**Comment by Howardyangyixuan** [comment]
> You can git pull.
> 
> I've tested training both autoencoder and SVR, and fixed path and reload issue in the demo.
> You can now try : `python train.py --demo --demo_input YOUR_PATH.obj --reload_model_path YOUR_PATH/network.pth --template_type SQUARE`
> 
> Note that the pretrained models are only autoencoders. If you want to do single-view, you have to train new models.
> 
> Best regards,
> Thibault

Great thanks for your fast response and swift change. It seems to work well. However, it requires torchvision version 0.3.0 or later, which means you need pytorch 1.2 or later, and it recursively needs cuda 9.2 or later. Otherwise, you will meet some [problem](https://github.com/pytorch/pytorch/issues/22539) due to an old version of torchvision and have to change some code. I will try it later. But again great thanks!

**Comment by Leerw** [comment]
Are there available for more nb_primitive pretrained models other than 1 patch?

**Comment by ThibaultGROUEIX** [comment]
No, all trained models for this branch are [here]( https://drive.google.com/a/polytechnique.org/uc?id=1mlA57o7n7CK9u8RpYS_RekTQN7RTNjhl&export=download).
Best regards

**Comment by Leerw** [comment]
> No, all trained models for this branch are [here](https://drive.google.com/a/polytechnique.org/uc?id=1mlA57o7n7CK9u8RpYS_RekTQN7RTNjhl&export=download).
> Best regards

Thanks.
