### ISSUE TITLE
Sharing training data on public storage?

### ISSUE THREAD

**Issue by zck119** [ThibaultGROUEIX/AtlasNet#5]
It seems that the training data is stored on mega.nz, which has a quota of a few GB for downloading, while the training data is a 12GB zip file, so it's impossible to download it at once. Is there any chance that the data is put on public storage that can be freely downloaded?

**Comment by ThibaultGROUEIX** [comment]
hi ! -  i'm away until the 13th of May. I think you face this issue because you try to save the files on your own mega.nz account which is not neccessary. you should just log out of any account you have and download the files directly. it use to work. i'll investigate more next week if neccessary.

**Comment by zck119** [comment]
Thanks @ThibaultGROUEIX,  it seems that mega.nz has a transfer limit of ~5GB per a few hours for each IP address, regardless of whether I've logged in to an account. I've successfully downloaded the data after using multiple IPs.

**Comment by ThibaultGROUEIX** [comment]
@zck119 Thanks for your feedback. I've moved the data to the public cloud of ENPC school, there shouldn't be any more issues in downloads. Can you close the issue if everything's fine on your end ?
