### ISSUE TITLE
Mapping 2d to 3d

### ISSUE THREAD

**Issue by xiang-zhu127** [ThibaultGROUEIX/AtlasNet#50]
Hello,
I was wondering if there is any way to map part of a 2d image to the 3d mesh generated. like for the airplane, can i automatically map the left wing in the image to the left wing of the mesh etc..

Any help would be appreciated thanks.

**Comment by ThibaultGROUEIX** [comment]
Hi @xiang-zhu127,
This is beyond the scope of the current code. 

One possibility would be to reproject the generated mesh to the image and use the reprojection to texture the mesh. This would work if the generated mesh were in image coordinates which is not the case in this code. The meshes are predicted in a canonical frame. Other works showed that AtlasNet can also generate meshes in image coordinate, but you would have to change the code and retrain the method.
 
Hope this helps,
Cheers
