### ISSUE TITLE
where does the HtmlGenerator module come from?

### ISSUE THREAD

**Issue by cdluminate** [ThibaultGROUEIX/AtlasNet#51]
I did `pip search`, `google search`, [`github search`](https://github.com/search?l=Python&p=2&q=HtmlGenerator&type=Repositories) and just could not found this module.

**Comment by ThibaultGROUEIX** [comment]
Hi @cdluminate,
It comes from netvision :https://github.com/palanglois/netvision
Netvision is a tool we developed with @palanglois to embed 3D models in webpages. We found it useful for collaborative research to simply share webpages. Netvision is now pretty obsolete with the development of PyPlot but at the time of the last AtlasNet refacto, there was no such tools.
Netvision should still work though, and is not supposed to give you any trouble.
Best regards,
Thibault

**Comment by cdluminate** [comment]
@ThibaultGROUEIX thank you for the astonishingly fast response. this is really helpful!
