### ISSUE TITLE
poor performance in my own trained model

### ISSUE THREAD

**Issue by dangchengliang** [ThibaultGROUEIX/AtlasNet#52]
Hi,Thank you for your great works and i benefit so much from it when I read your paper .when I  run your code ,and trained the datasets of shapenet,I got the same fscore as you but got  poor models compared to yours.I didn't change your parameter or anyohther codes. Can you tell me what's wrong witn my operate.I sincerely hope you can give me some help. 
My Best wishes!

**Comment by zyz-notebooks** [comment]
What is your pytorch version, my 1.6 does not work

**Comment by dangchengliang** [comment]
My pytorch version is 1.6. The project works well in this environment.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultGROUEIX/AtlasNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月6日(星期天) 下午5:06
收件人:&nbsp;"ThibaultGROUEIX/AtlasNet"<AtlasNet@noreply.github.com&gt;;
抄送:&nbsp;"熙熙"<2897913140@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ThibaultGROUEIX/AtlasNet] poor performance in my own trained model (#52)





 
What is your pytorch version, my 1.6 does not work

**Comment by ThibaultGROUEIX** [comment]
Hi @dangchengliang ,
It's hard to say. Could you share a qualitative example? 
Did you train the single-view example and the autoencoder?
Best wishes,
Thibault

**Comment by dangchengliang** [comment]
> Hi @dangchengliang ,
> It's hard to say. Could you share a qualitative example?
> Did you train the single-view example and the autoencoder?
> Best wishes,
> Thibault

**Comment by dangchengliang** [comment]
&nbsp;I have trained the autoencoder using the command 'python train.py --shapenet13',and didn't change any things of your code.I got a fscore of 0.819.in addition, I didn't train the&nbsp;single-view example.I attach a model of&nbsp;AtlasnetReconstruction to the&nbsp;attachment. I got this ply file through the command 'python train.py --demo' and I changed the path of 'network.pth' of my own.&nbsp;
&nbsp;I think I may have done the wrong step.
&nbsp;Looking forward to your reply.Thanks.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultGROUEIX/AtlasNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月6日(星期天) 晚上7:30
收件人:&nbsp;"ThibaultGROUEIX/AtlasNet"<AtlasNet@noreply.github.com&gt;;
抄送:&nbsp;"熙熙"<2897913140@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ThibaultGROUEIX/AtlasNet] poor performance in my own trained model (#52)





 
Hi @dangchengliang ,
 It's hard to say. Could you share a qualitative example?
 Did you train the single-view example and the autoencoder?
 Best wishes,
 Thibault
