### ISSUE TITLE
poor performance

### ISSUE THREAD

**Issue by dangchengliang** [ThibaultGROUEIX/AtlasNet#53]
I have trained the autoencoder using the command 'python train.py --shapenet13',and didn't change any things of your code.I got a fscore of 0.819.in addition, I didn't train the single-view example.I attach a model of 
![VMTX2K`UG863AI@55 YKBE9](https://user-images.githubusercontent.com/65058609/92386630-bb43aa00-f146-11ea-8d4e-21db246c447d.png) AtlasnetReconstruction to the attachment. I got this ply file through the command 'python train.py --demo' and I changed the path of 'network.pth' of my own.
I think I may have done the wrong step.
Looking forward to your reply.Thanks.

**Comment by ThibaultGROUEIX** [comment]
Dear @dangchengliang ,
Thanks for reaching out,

Can you double-check that you train for auto-encoder and test with the same auto-encoder? I think the demo is doing SVR by default.

Best,
-Thibault
