### ISSUE TITLE
Change The Encoder

### ISSUE THREAD

**Issue by dangchengliang** [ThibaultGROUEIX/AtlasNet#54]
Hello:
I have changed the part of encoder from pointNet to PointNet++.The Fscore is higher than orignal paper,but the 3d mesh
generated by AtlasNet is poorer.I wonder if you have tried PointNet++ before.
Any help would be appreciated, thanks.

**Comment by ThibaultGROUEIX** [comment]
Hi @dangchengliang 
Yes, without any luck. It always gave me poorer results that PN (both qualitatively and quantitatively), but the code at the time were probably more buggy as well.
If I were you, i would look at recent shape reconstruction paper doing auto-encoders and try to see if they use anything more recent than PN...
Best regards

**Comment by ThibaultGROUEIX** [comment]
Hi, i am curious if you had any luck with this?
-Cheers,

**Comment by dangchengliang** [comment]
> Hi, i am curious if you had any luck with this?
> -Cheers,

Hi, I'm sorry to be so late reply to you firstly! I've tried several other encoders,such as PointNet++, SO-Net,DGCNN  , but the results have been disappointing. I have no idea what's  with this issue... 
Next I'm going to try the encoder of FoldingNet.Do you have any Suggestions?Any help would be appreciated, thanks.
Best regards.

**Comment by ThibaultGROUEIX** [comment]
Not really, as i have mentioned, i have also been searching for a more recent point cloud encoder without any luck and i am now working on something else at the moment,
--Best regards
