### ISSUE TITLE
Any specific reason to sample the point cloud with replacement? 

### ISSUE THREAD

**Issue by sagniklp** [ThibaultGROUEIX/AtlasNet#55]
https://github.com/ThibaultGROUEIX/AtlasNet/blob/2baafa5607d6ee3acb5fffaaae100e5efc754f99/dataset/dataset_shapenet.py#L191

**Comment by ThibaultGROUEIX** [comment]
Dear @sagniklp 
Thanks for reaching out

Yes, some ground truth point clouds are very small. The overall number of points in those can be less than `self.num_sample` which gives an error if you sample without replacement.

Best regards,
-Thibault
