### ISSUE TITLE
Changing image path

### ISSUE THREAD

**Issue by mschweig** [ThibaultGROUEIX/AtlasNet#56]
Hi, 
I am trying to change the image for the demo. According to readme following syntax should be working, right? 
`python train.py --demo --demo_input_path /content/AtlasNet/doc/pictures/plane_input_demo.png  --reload_model_path /content/AtlasNet/training/trained_models/atlasnet_autoencoder_25_squares/network.pth`

Unfortunately, I am getting a error: 

```
File "train.py", line 18, in <module>
    trainer = trainer.Trainer(opt)
  File "/content/AtlasNet/training/trainer.py", line 29, in __init__
    os.mkdir(self.opt.training_media_path)
FileNotFoundError: [Errno 2] No such file or directory: 'log/02020-11-19T11:57:59.131672/training_media'
```
Could you please help me changing the image. 

Thank you.

**Comment by ThibaultGROUEIX** [comment]
Hi @mschweig ,

It fails because you are missing all the network specs with `--reload_model_path ` (it would need much more parameters).
You can use `dir_name` instead which loads everything the model needs.

For instance, you can you : 
```shell
python train.py --demo --demo_input_path doc/pictures/visdom2.png --dir_name ./training/trained_models/atlasnet_autoencoder_25_squares/
```

Best regards,
-Thibault
