### ISSUE TITLE
What changes have you made between v2.2 and v3.0?

### ISSUE THREAD

**Issue by swords123** [ThibaultGROUEIX/AtlasNet#57]
I see that V3.0 code has been greatly improved in performance. What changes have you made?

**Comment by ThibaultGROUEIX** [comment]
Hi @swords123 

I am sorry for the late reply, I missed this issue.

Between v2 and v3, I redesigned the training framework. It's much more modular (handles different kind of architectures, multi-gpu, different templates...)

Where do you see that it improves performance? It should not change much.

Thanks,
Thibault
