### ISSUE TITLE
Question about loss

### ISSUE THREAD

**Issue by Minglin-Chen** [ThibaultGROUEIX/AtlasNet#58]
Hi, I realize that you use Chamfer loss [here](https://github.com/ThibaultGROUEIX/AtlasNet/blob/ecd64f8242cc33d7e9ea83027c9d9245b5153dac/training/trainer_loss.py#L48) which always has a positive value. However, the loss curve shown in figure [here](https://github.com/ThibaultGROUEIX/AtlasNet/blob/ecd64f8242cc33d7e9ea83027c9d9245b5153dac/doc/training.md) has a negative value. That really confuses me.

I want to know whether the loss used in the figure is Chamfer loss or other loss?

**Comment by ThibaultGROUEIX** [comment]
Hi, 
It's because we plot the log of the chamfer distance. It helps to see when the network has converged.
Let me know if you have more feedback / question. 
Best regards,
Thibault

**Comment by Minglin-Chen** [comment]
Thanks, Thibault. It is clear for me.
