### ISSUE TITLE
HtmlGenerator

### ISSUE THREAD

**Issue by HeCraneChen** [ThibaultGROUEIX/AtlasNet#59]
Thanks for the amazing code! I have one question though. In html_report, and init_html_report, you imported a package called HtmlGenerator. Is this a file written by yourself? If so, could you please upload this as well? 

Or, where did you find this package? I think I'm only able to run a similar one. "pip install htmlgenerator" seems to be installing something else.

**Comment by ThibaultGROUEIX** [comment]
Hi @HeCraneChen 

It's a submodule we wrote with @palanglois.

Make sure to clone AtlasNet and it's submodule like this :
`git clone --recurse-submodules https://github.com/ThibaultGROUEIX/AtlasNet.git`

The repo for the submodule is located [here]( https://github.com/palanglois/netvision).

Best regards,
Thibault

**Comment by HeCraneChen** [comment]
Thanks!
