### ISSUE TITLE
The corresponding normalized mesh

### ISSUE THREAD

**Issue by wang-ps** [ThibaultGROUEIX/AtlasNet#6]
I downloaded the corresponding normalized mesh (Only 58Mb) from the link you provided. I found that the number of the mesh was much smaller than the corresponding point cloud.
Could you please provide  the full dataset of the corresponding normalized mesh? Thank you!

**Comment by ThibaultGROUEIX** [comment]
Hi, I used the normalized meshes to evaluate the method with a mesh-based distance : the METRO distance. It is quite intractable to compute on all of Shapenet, so I ran it on the subset : the one you downloaded. If, for example,  you wish to compare with AltasNet, you should reuse the same subset. If you have something else in mind entirely for the normalized mesh, the best thing to do would be to directly download shapenetcorev2 from their website, and process each mesh to be centered, and in the unit ball. Let me know if i can help you further. Did you have issues with the download like in #5  ?

**Comment by wang-ps** [comment]
I see. Thank you so much for your immediate reply! I have successfully downloaded all the data you provided (no issue like #5).
By the way, I have also downloaded the ShapeNetCore.v2 from the official site of ShapeNet. When normalizing the meshes, how do you compute the unit bounding sphere?  I did implement a simple bounding sphere algorithm. But after normalization, the scale of mesh is still slightly different from the mesh you provided.
I like your paper very much and get many inspirations from it. To fully understand the algorithm, I have read your code. It seems that when training the Single Image to Shape (i.e. train_SVR_AtlasNet.py) network, the parameters of 3D decoder are fixed. Does this have more benefit than training the image encoder and 3D decoder together?

**Comment by ThibaultGROUEIX** [comment]
SVR question : yes. In fact the best setting (we found out later) is to
- train decoder with the autoencoder
- fix decoder, and train encoder with SVR
- finetune SVR by freeing the decoder

To normalize : 
- center the mesh (subtract the mean)
- find the radius of the pointcloud i.e the max  over all the points of their L2 distance
- project it to unit ball by dividing each point by the radius.

This should reproduce exactly our normalized meshes.

**Comment by wang-ps** [comment]
Thank you! 👍

**Comment by ThibaultGROUEIX** [comment]
No problem, good luck !

**Comment by wang-ps** [comment]
Hi, I am aslo doing a research project related with reconstructing the 3D shape from one 2D image, and want to do some comparison with your work.
In the section 5.3, you mentioned that you randomly selected 260 shapes from 13 categories and ran ICP to align the outputs.
Could you kindly provide the 260 filenames which are used in this comparison? 
And is it possible to provide the aligned results of PSG?

**Comment by ThibaultGROUEIX** [comment]
I guess you're mentionning section 5.2. I've uploaded the files names  in AtlasNet/inference/, 
i'll update ICP's results on PSG this week. Good luck !

**Comment by ThibaultGROUEIX** [comment]
there you go : https://cloud.enpc.fr/s/3a7Xg9RzIsgmofw

**Comment by wang-ps** [comment]
Thank you so much!
