### ISSUE TITLE
Whether it will affect performance if I train the model within one class or across different classes?

### ISSUE THREAD

**Issue by Wi-sc** [ThibaultGROUEIX/AtlasNet#60]
Hi, thanks for your great work. I'm also interested in the single view reconstruction but I'm new to it. I want to know if Atlasnet can generate different class objects only given one model. Or I should train multiple models like a model for the plane, a model for the chair, and so on. And whether it would affect performance?

**Comment by ThibaultGROUEIX** [comment]
Hi @Wi-sc 
In the paper, we train a single AtlasNet on all categories. You can also train a separate model for each category, performances will be better for large categories (>300 samples more or less) and worse for small categories  
Best regards
