### ISSUE TITLE
The dataset download problem

### ISSUE THREAD

**Issue by yukai-lin-git** [ThibaultGROUEIX/AtlasNet#61]
(atlasnet) yukailin@yukailin-TUF-GAMING-FX504GD-FX80GD:/media/yukailin/SSD/Desktop/YK-Research/AtlasNet$ sudo bash dataset/download_shapenet_pointclouds.sh 
When using the provided data make sure to respect the shapenet [license](https://shapenet.org/terms).
mkdir: 無法建立 「data」 目錄: 檔案已存在
--2021-04-01 20:13:34--  https://docs.google.com/uc?export=download&confirm=&id=1MMCYOqSalz77dduKahqDEQKFP9aCvUCy
正在查找主機 docs.google.com (docs.google.com)... 172.217.24.14, 2404:6800:4012:1::200e
正在連接 docs.google.com (docs.google.com)|172.217.24.14|:443... 連上了。
已送出 HTTP 要求，正在等候回應... 200 OK
長度: 未指定 [text/html]
儲存到：`data/ShapeNetV1PointCloud.zip'

data/ShapeNetV1PointCloud.zip                    [ <=>                                                                                          ]   3.07K  --.-KB/s    於 0s      

2021-04-01 20:13:34 (6.02 MB/s) - 已儲存 `data/ShapeNetV1PointCloud.zip' [3139]

Archive:  ShapeNetV1PointCloud.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  ShapeNetV1PointCloud.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of ShapeNetV1PointCloud.zip or
        ShapeNetV1PointCloud.zip.zip, and cannot find ShapeNetV1PointCloud.zip.ZIP, period.

Is it something wrong with the file download_shapenet_pointclouds.sh,
like the line gdrive_download 1MMCYOqSalz77dduKahqDEQKFP9aCvUCy data/ShapeNetV1PointCloud.zip in this file.
Thank you.

**Comment by ThibaultGROUEIX** [comment]
Hi @yukai-lin-git 
Yes, this a a known issue with google drive. it blocks downloads if the traffic is too large.  I suggest to try again in 1 or 2 days.
I need to move the data to another  storage solution.
best regards,

**Comment by yukai-lin-git** [comment]
I will try the file in1 or 2 days.
Thank you so much.

**Comment by Ade-Pyaar** [comment]
Hello, the problem still persists, please help to solve it.

**Comment by ThibaultGROUEIX** [comment]
Hi @Ade-Pyaar 

Can you point me toward a free storage solution which can host the >100Gb of data and offer larger download traffic caps? I was not able to find one unfortunately, but i am not very knowledgeable there,

Best regards,
Thibault

**Comment by Ade-Pyaar** [comment]
I do not know any cloud platform that can offer >100GB of storage for free.

**Comment by ErnieLud** [comment]
> i have download this ,if you need it, you can connect me

hello sir, i really need [this](https://github.com/ThibaultGROUEIX/AtlasNet/blob/V2.2/data/download_data.sh) data, did you managed to download it ? please

**Comment by ghost** [comment]
does anyone have the `customShapeNet` directory from the AtlasNet project version 2.2 ? Please I really need its content, I would be extremely grateful. This directory was supossedly downloaded from [this](https://github.com/ThibaultGROUEIX/AtlasNet/blob/V2.2/data/download_data.sh) script but links are broken already. I just need the 02691156 category under the `customShapeNet` directory

**Comment by ThibaultGROUEIX** [comment]
Hi,
It seems, the Google drive traffic cap may be lifted if the download is manual instead of by command line :
https://drive.google.com/drive/folders/1If_-t0Aw9Zps-gj5ttgaMSTqRwYms9Ag?usp=sharing

I have also put the same data on Kaggle:
https://www.kaggle.com/thibeix/atlasnet-data

Please make sure to unzip the archives in the right places : 
```shell
cd AtlasNet
mkdir data
unzip ShapeNetV1PointCloud.zip -d ./data/
unzip ShapeNetV1Renderings.zip -d ./data/
unzip metro_files.zip -d ./data/
unzip trained_models.zip -d ./training/
```
Let me know if it works?

Best,
-Thibault

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
