### ISSUE TITLE
Downloading ground-truth point clouds

### ISSUE THREAD

**Issue by ghost** [ThibaultGROUEIX/AtlasNet#63]
Hello,
I am trying to run this [script](https://github.com/ThibaultGROUEIX/AtlasNet/blob/V2.2/data/download_data.sh) from AtlasNet v2.2 but it seems that download links are broken. Where can I find the data?
I really need to get the `customShapeNet` directory for [this](https://github.com/chenhsuanlin/photometric-mesh-optim#shapenet-point-clouds) project. 

Also, when I try to run [this](https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/dataset/download_shapenet_pointclouds.sh) script of the newer AtlasNet version, I get the following error:
"Archive:  ShapeNetV1PointCloud.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive."

Best regards

**Comment by ThibaultGROUEIX** [comment]
Hi @ErnieLud ,
Yes this is the same as https://github.com/ThibaultGROUEIX/AtlasNet/issues/61
Sorry I do not have a great solution there. Please let me know if something comes to mind
Best regards
Thibault

**Comment by XiaoshuiHuang** [comment]
you can try  "baidu wangpan" which has 2TB free storage https://pan.baidu.com/

**Comment by ThibaultGROUEIX** [comment]
Hi @ErnieLud ,
I have updated the answer in #61,
Best
