### ISSUE TITLE
the download links not works

### ISSUE THREAD

**Issue by derrick-xwp** [ThibaultGROUEIX/AtlasNet#64]

**Comment by ThibaultGROUEIX** [comment]
Hi @derrick-xwp ,

please check out https://github.com/ThibaultGROUEIX/AtlasNet/issues/61
Do you know how other people handle this problem?

Best regards
Thibault

**Comment by ThibaultGROUEIX** [comment]
Hi @derrick-xwp ,
I updated the answer in #61
