### ISSUE TITLE
is pretrained model available?

### ISSUE THREAD

**Issue by derrick-xwp** [ThibaultGROUEIX/AtlasNet#65]

**Comment by ThibaultGROUEIX** [comment]
Hi @derrick-xwp ,
yes, just run the demo, they will be downloaded automatically
best regards

**Comment by sumai-1998** [comment]
change the S1 value in .sh and type on the web browser manually, i can't download with .sh too

**Comment by ThibaultGROUEIX** [comment]
Hi @4ssass1n0r ,
I am sorry, I don't understand what you mean. Can you add some context please?
Best regards

**Comment by sumai-1998** [comment]
> Hi @4ssass1n0r ,
> I am sorry, I don't understand what you mean. Can you add some context please?
> Best regards



> Hi @4ssass1n0r ,
> I am sorry, I don't understand what you mean. Can you add some context please?
> Best regards

i mean for example in download_shapenet_pointclouds.sh there is a cmd like 
"wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=$1" -O $2"
just change the $1 value and get 
https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=1MMCYOqSalz77dduKahqDEQKFP9aCvUCy
then paste the link in edge and download.
I can't download the dateset by run './download_shapenet_pointclouds.sh', it just stuck.

**Comment by sumai-1998** [comment]
> > Hi @4ssass1n0r ,
> > I am sorry, I don't understand what you mean. Can you add some context please?
> > Best regards
> 
> > Hi @4ssass1n0r ,
> > I am sorry, I don't understand what you mean. Can you add some context please?
> > Best regards
> 
> i mean for example in download_shapenet_pointclouds.sh there is a cmd like
> "wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=$1" -O $2"
> just change the $1 value and get
> https://docs.google.com/uc?export=download&confirm=$CONFIRM&id=1MMCYOqSalz77dduKahqDEQKFP9aCvUCy
> then paste the link in edge and download.
> I can't download the dateset by run './download_shapenet_pointclouds.sh', it just stuck.

All download.sh  the same

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
