### ISSUE TITLE
What's the best hyper parameter of this porject?

### ISSUE THREAD

**Issue by sumai-1998** [ThibaultGROUEIX/AtlasNet#66]
so many opts, and in training.md, just two default training setting command. 
I want to train with the best parameter setting

**Comment by ThibaultGROUEIX** [comment]
Hi @4ssass1n0r,
Thanks for using the code.
Do you want to do single-image reconstruction or auto-encoders?
Best,
Thibault

**Comment by ThibaultGROUEIX** [comment]
In any case, you can use the command line i provided for those two cases, there should be close to optimal. At least, they correspond to what we do in the paper.
https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default

Have a nice day,
Thibault

**Comment by sumai-1998** [comment]
> In any case, you can use the command line i provided for those two cases, there should be close to optimal. At least, they correspond to what we do in the paper.
> https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default
> 
> Have a nice day,
> Thibault

every thanks!  I was running ```python train.py --shapenet13 --visdom_port 8890''', it seems this is no better than 
[https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default]
right?

**Comment by sumai-1998** [comment]
> > In any case, you can use the command line i provided for those two cases, there should be close to optimal. At least, they correspond to what we do in the paper.
> > https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default
> > Have a nice day,
> > Thibault
> 
> every thanks! I was running ```python train.py --shapenet13 --visdom_port 8890''', it seems this is no better than
> [https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default]
> right?

I almost done with this command, I will compare the three cmd and their performance, today I just download the dataset, so I asked this question,
thanks a lost

**Comment by sumai-1998** [comment]
but if anyone have a better parameter setting, I hope you can share here thanks

**Comment by ThibaultGROUEIX** [comment]
> > In any case, you can use the command line i provided for those two cases, there should be close to optimal. At least, they correspond to what we do in the paper.
> > https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default
> > Have a nice day,
> > Thibault
> 
> every thanks! I was running ```python train.py --shapenet13 --visdom_port 8890''', it seems this is no better than
> [https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default]
> right?

No `python train.py --shapenet13 --dir_name log/atlasnet_autoencoder_25_squares --nb_primitives 25 --template_type "SQUARE" ` is better. Otherwize you train with a single sphere primitive. You can check the defaults in this webpage : https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md

**Comment by sumai-1998** [comment]
> > > In any case, you can use the command line i provided for those two cases, there should be close to optimal. At least, they correspond to what we do in the paper.
> > > https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default
> > > Have a nice day,
> > > Thibault
> > 
> > 
> > every thanks! I was running ```python train.py --shapenet13 --visdom_port 8890''', it seems this is no better than
> > [https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md#autoencoder-default]
> > right?
> 
> No `python train.py --shapenet13 --dir_name log/atlasnet_autoencoder_25_squares --nb_primitives 25 --template_type "SQUARE" ` is better. Otherwize you train with a single sphere primitive. You can check the defaults in this webpage : https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/training.md

I got it now,   thanks bro
