### ISSUE TITLE
When I compile the nndistane

### ISSUE THREAD

**Issue by blister1824** [ThibaultGROUEIX/AtlasNet#7]
I used Python2.7 Pytorch0.1.12
but when I compile the build.py in file nndistance
I meet a strange error just like

> /lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGenerateHalfType.h:9:14:
error: unknown type name ‘half’
 #define real half

I wanna know if anyone meet the same problem?????

**Comment by ThibaultGROUEIX** [comment]
Stange I've never heard of this issue before. In case it helps, i use gcc 5.4.1 My best guess would be to reinstall pytorch with ```conda install pytorch=0.1.12 cuda80 -c soumith```

**Comment by blister1824** [comment]
It seems that the cuda version causes the bug..My cuda version is 9.0 and I try `conda install pytorch=0.1.12 cuda90 -c soumith` but it fails to find the package cuda90.

**Comment by ThibaultGROUEIX** [comment]
yes, i dont think 1.12 is compatible with cuda 9. you can either downgrade to cuda 8 or try to manually compile pytorch from the specific commit i point out in the readme (otherwise it won't work). let me know if either of these two solutions work.

**Comment by blister1824** [comment]
hey guy i try the second solution and luckily now i can build the nndistance. @ThibaultGROUEIX 
However, I want to know after i run the script _demo.py_, where does the file `output.ply` locate?
Actually i think the function `write_ply()` in the last line outputs the .ply file and i check the function returns true, but i can't find the .ply file T.T

**Comment by ThibaultGROUEIX** [comment]
Great! The generated file is in /data/. I'm closing this since the main issue has been solved.
