### ISSUE TITLE
(Meshlab Visualization Trick ) Parts of faces flipped in the generated obj by train.py --demo

### ISSUE THREAD

**Issue by ZENGYIMING-EAMON** [ThibaultGROUEIX/AtlasNet#71]
Hi, the link of Meshlab Visualization Trick is broken, and I wonder why some of the faces flipped in the generated obj and is it possible to fix it quickly instead of selecting them face by face?

**Comment by ThibaultGROUEIX** [comment]
Hi @ZENGYIMING-EAMON ,
Thanks for your question. 
Some faces are flipped because nothing in the loss constrains face orientation. I did not understood  what your are suggesting, but mostly it boils down to selecting "double-sided rendering"  in meshlab.

Best regards
