### ISSUE TITLE
V2.2 dataset links are invalid (not the ones from V1)

### ISSUE THREAD

**Issue by TARDISImmanuel** [ThibaultGROUEIX/AtlasNet#73]
Hello,
I would like to download the datasets from branch **V2.2**, but the links in this script (https://github.com/ThibaultGROUEIX/AtlasNet/blob/V2.2/data/download_data.sh) are invalid. 
(Not the datasets from V1, the datasets from V1 are good to download from those google drive links.)

I would really appreciate it If anyone has these datasets and could kindly contact me. Many thanks in advance!

**Comment by ThibaultGROUEIX** [comment]
Hi @TARDISImmanuel,
Why not download the latest datasets?
Best regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
