### ISSUE TITLE
some data download questions

### ISSUE THREAD

**Issue by pxing6** [ThibaultGROUEIX/AtlasNet#74]
hi,friend,your work is really charming,but i can not download your V2 version datas,such as customShapeNet and ShapeNetRendering,can you upgrades these datasets download links,thank you very much

**Comment by ThibaultGROUEIX** [comment]
Hi pxing6,
Thanks for your interest!
Have you tried all these solutions ? https://github.com/ThibaultGROUEIX/AtlasNet#a-note-on-data
Cheers
-Thibault

**Comment by pxing6** [comment]
thanks for your reply.Yes,i have tried all these solutions,these links are vaild,and i have downloaded your AtlasnetV1 project and datasets(ShapeNetV1PointCloud,ShapeNetV1Renderings).But i can not download your AtlasnetV2 datasets such as customshapenet(https://cloud.enpc.fr/s/j2ECcKleA1IKNzk) and shapenetrendering(https://cloud.enpc.fr/s/S6TCx1QJzviNHq0),these download links are invalid.I really need them,can you help me.thank you very much.

**Comment by pxing6** [comment]
![qq_pic_merged_1654421670364](https://user-images.githubusercontent.com/84260397/172044425-2fb30960-15de-4fa2-a179-9e6b334e8d6c.jpg)
two links are invalid,and i really need these two datasets,can you help me,thanks.

**Comment by ThibaultGROUEIX** [comment]
Hi, 
is this from a previous version of the repo?
Best
-Thibault

**Comment by pxing6** [comment]
hi,Thibault
yes, they are repo from previous version and i need them(include customShapenet and ShapeNetRendering),could you help me? thank you very much.

**Comment by ThibaultGROUEIX** [comment]
HI,

I don't support this version anymore.
You can try these links 
renderings : https://cloud.enpc.fr/s/axiC3FHS374FgEf
points : https://cloud.enpc.fr/s/JNf3NAxGbQoQsKY

Cheers,
Thibault

**Comment by pxing6** [comment]
OK,i will try to download these link.thanks for your reply

**Comment by pxing6** [comment]
OK,i will try to download these links.thanks for your reply.

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
