### ISSUE TITLE
the pretrained resenet model under shapenet

### ISSUE THREAD

**Issue by takeshie** [ThibaultGROUEIX/AtlasNet#76]
hi,friend,your work is really charming, I want to follow this project. could you release the pretrained resenet model under shapenet?

**Comment by ThibaultGROUEIX** [comment]
Hi, It is released in the README.md.
Maybe i did not understand your question?

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
