### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by yufeng9819** [ThibaultGROUEIX/AtlasNet#77]
Hey! It is a wonderful work. 
And I have a quetions  about data. I visulise the dataset you provided and find that some point cloud can not match with 2D images. Some cases are as follows. 
![image](https://user-images.githubusercontent.com/113972543/194116358-678fb023-52c0-49c1-a815-443175e7a7fd.png)
![image](https://user-images.githubusercontent.com/113972543/194116486-2b1b4d22-d00c-4665-ae93-781338958a75.png)

I check out the way I visulise and I think I correctly visulise image and point cloud in dataset since in some categories( such as airplane and chair) images can be matched correctly with the point cloud. 

Looking forward to your reply.

**Comment by ThibaultGROUEIX** [comment]
HI @yufeng9819 
Could they be the correct object but in canonical orientation and normalized?
Cheers,

**Comment by yufeng9819** [comment]
Thanks for your reply! I think you are right!
