### ISSUE TITLE
AtlasNet checkpoint not available

### ISSUE THREAD

**Issue by apicis** [ThibaultGROUEIX/AtlasNet#78]
Hi @ThibaultGROUEIX, thank you for sharing the code.

When downloading checkpoint of the model using the *trained_models/download_models.sh*  (https://cloud.enpc.fr/s/c27Df7fRNXW2uG3/download) related to the version 2.2 of the source code, the link seems to be broken or no longer available. Could you please help me with this?

Thanks.

**Comment by ThibaultGROUEIX** [comment]
Hi @apicis 
I am not sure what you are refering to. Can you point to `trained_models/download_models.sh` ? 
Are you perhaps not on the latest master branch?
The models are here : https://drive.google.com/drive/folders/1If_-t0Aw9Zps-gj5ttgaMSTqRwYms9Ag

best regards,
Thibault

**Comment by kochsebastian** [comment]
Do you still have the checkpoint compatible with V2.2? The state dict of the current ones is not compatible with V2.2

**Comment by apicis** [comment]
@ThibaultGROUEIX 

> Can you point to `trained_models/download_models.sh` ?

https://github.com/ThibaultGROUEIX/AtlasNet/blob/V2.2/trained_models/download_models.sh

> Are you perhaps not on the latest master branch? 

The [README.md](https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/README.md) file states V2.2 is "more linear, script like, may be easier to understand at first" so I started from that. Do you have another suggestion to start? 

Thanks

**Comment by ThibaultGROUEIX** [comment]
> 

Hi @kochsebastian  and @apicis ,

Unfortunately no, I recommend using the latest version of the code.

Thibault

**Comment by kochsebastian** [comment]
The problem I have is that V2.2 seems to contain models that do 3D-3D reconstruction (AE_AtlasNet, AE_AtlasNet_SPHERE as in [model.py](https://github.com/ThibaultGROUEIX/AtlasNet/blob/V2.2/auxiliary/model.py)). But the models on master appear to do 2D-3D reconstruction as described in [demo.md](https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/demo.md). However I am interested in 3D-3D autoencoding.

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
