### ISSUE TITLE
Question about train and test strategy

### ISSUE THREAD

**Issue by yufeng9819** [ThibaultGROUEIX/AtlasNet#79]
Hi! Sorry for disturb you again.

I want to ask questions about train and test strategy. In your code, you set opt.shapenet13==True. So does it means that you first train your network on all categories and then test on each class to get the experiment metrics data of every single class.

Looking forward to your reply!

**Comment by ThibaultGROUEIX** [comment]
We train on all categories at once for the results in the main paper.
Best regards,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
