### ISSUE TITLE
pymesh library

### ISSUE THREAD

**Issue by tang-y-q** [ThibaultGROUEIX/AtlasNet#80]
could you please give me a window version whl file for pymesh ? I can't find the right pymesh library.
thanks so much!

**Comment by ThibaultGROUEIX** [comment]
I do not maintain Pymesh so I can not help you with this one.
You could either :
- remove the dependency on pymesh, it should not be critical
- contact the Pymesh author to get a wheel or compile it yourself
Best regards
Thibault
