### ISSUE TITLE
Compile Metro Distance (GPL3 Licence)

### ISSUE THREAD

**Issue by tang-y-q** [ThibaultGROUEIX/AtlasNet#81]
Hi i'm sorry to bother you again.
    when I used the code you give me to trying to build metro distance, I found that it could not be compiled successfully. 
    It will indicate that the system path cannot be found. The results are shown as follows:
![捕获](https://user-images.githubusercontent.com/80810163/195549457-59f55be2-4516-4da1-a72a-733acd25ba3a.PNG)
    could you please give some advice to solve this problem.
    thanks a lot!

**Comment by ThibaultGROUEIX** [comment]
Hi Tang, 
It's very hard for me to help with so little info. I would guess you need to change your path somewhere
Best regards,
Thibault
