### ISSUE TITLE
Question About Visulization

### ISSUE THREAD

**Issue by yufeng9819** [ThibaultGROUEIX/AtlasNet#82]
Hey! Sorry to disturb you again!

I want to know if there any effective tools by python  to visulize .obj file and save it to .png (except for meshlab).

Thanks for your reply!

**Comment by ThibaultGROUEIX** [comment]
You could look into 
trimesh, pytorch3d, nvdiffrast, moderngl, ...
Cheers,
Thibault

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
