### ISSUE TITLE
Unable to find normalised mesh dataset in AtlasNetv2

### ISSUE THREAD

**Issue by Hasindri** [ThibaultGROUEIX/AtlasNet#85]
The link given for normalised mesh dataset, "https://cloud.enpc.fr/s/RATKsfLQUSu0JWW/download", is broken. Can you kindly fix it? or give me a working link for this dataset, I am trying to reproduce your results for a research.

**Comment by ThibaultGROUEIX** [comment]
Hi @Hasindri 

I am assuming you are referring to the data used in the metro distance evaluation. 
Following the readme here : https://github.com/ThibaultGROUEIX/AtlasNet#a-note-on-data
You can find them under metro_files.

You seem to be following an old link, how did you find it?

Best regards,
Thibault

**Comment by Hasindri** [comment]
Thank you very much for your reply, I will refer these data.

I took this link from "https://github.com/theodeprelle/AtlasNetV2/blob/master/data/download.sh" in AtlasNetV2 repo.

**Comment by ThibaultGROUEIX** [comment]
Closing this since the issue is stale, feel free to reopen. Thanks a lot for for playing around with AtlasNet.
Cheers,
Thibault
