### ISSUE TITLE
Mesh Parametrization Checkerboard Visualization

### ISSUE THREAD

**Issue by tom-m-walker** [ThibaultGROUEIX/AtlasNet#86]
Hi,

Thanks for making your codebase available.

I'm interested in the surface parameterizations offered by this method. I was wondering how you produced the checkerboard visualizations which demonstrate the distortion? Apologies if I have missed it, but I can't find this code in the repo. Any tips on how to reproduce these results?

Many thanks,
Tom

**Comment by ThibaultGROUEIX** [comment]
@vokim may be able to help

**Comment by vokim** [comment]
@ThumbmasWalker Not sure which figure are you referring to. But AtlasNet produces a UV parameterization by construction: each 3D point was mapped from some 2D location. If you store these 2D locations as UV coordinates, in, say, OBJ file, you can apply any kind of material to it, including a checkerboard texture. You can simply add material header to OBJ file and manually create corresponding MTL file that references a 2D texture of your choice. 

We also visualize optimized UV maps after distortion minimization. For this, I would just use off-the-shelf geometric optimization (e.g., SLIM: https://github.com/MichaelRabinovich/Scalable-Locally-Injective-Mappings ) to get better UVs.

**Comment by tom-m-walker** [comment]
Thanks for the reply this is really helpful (I am coming from a machine learning background rather than a CG background so this is quite new to me). Are there any programs you would recommend to create the mtl file? Thanks again.

**Comment by tom-m-walker** [comment]
Don't worry, think I've figured it out!
All the best,
Tom
